### ISSUE TITLE
error[E0554]: `#![feature]` may not be used on the stable release channel  --> src/main.rs:1:1

### ISSUE THREAD

**Issue by ubuntupunk** [aedoq/i3-scratchmenu#1]
Does not compile with stable or beta compiler:

Feature attributes are only allowed on the nightly release channel. Stable or
beta compilers will not comply.

Erroneous code example:

```
#![feature(non_ascii_idents)] // error: `#![feature]` may not be used on the
                              //        stable release channel

**Comment by aedoq** [comment]
Fixed with 547df45a36b365d1d807235736e283274af21666. Thank you for the issue
